### ISSUE TITLE
datasource streaming and IframeOutputStream bug

### ISSUE THREAD

**Issue by lpand** [biomart/biomart-rc7#1]
Currently, retrieving of results by the front-end is done with streaming (with the streaming object declared inside datasource) and iframes (option declared within resultsPanel).
When the iframe option is given to the datasource widget, on the server the chosen processor will be given an instance of org.biomart.api.rest.IframeOutputStream as argument of setOutputStream. 

The IframeOutputStream class has the following bug:

This code is Groovy running in groovysh

``` Groovy
import org.biomart.api.rest.IframeOutputStream as Ifr
// RESULT: [import org.biomart.api.rest.IframeOutputStream as Ifr]
out = new Ifr('results', System.out, 'ascope'); // in this case the first and last param are random
// RESULT: org.biomart.api.rest.IframeOutputStream@962e703
out.sb // sb is the private StringBuffer field, and now is empty
// RESULT: 
out.write("ciao".getBytes()) // it wants an array of byte
// RESULT: null
out.sb
// RESULT: ciao
out.write(0x0a) // 0x0a == 10 == '\n'
// RESULT: null
out.sb // sb doesn't contain the return just submitted
// RESULT: ciao
```

This will cause the server to return only one row instead of the proper number, since all carriage returns are dropped.

Besides this bug, the point is also that it'd be nice to have a choice on the front-end to use iframes or different ways to get the data back.

**Comment by iwan** [comment]
What happens if you write:
out.write(Integer.decode("0x0a"))
or simply
out.write(10)
?

Maybe there's a problem with hex decoding...
